# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Susu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('aroma', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tatti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=20)),
                ('kyu', models.CharField(max_length=30)),
                ('pfft', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='susu',
            name='tatti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dard.Tatti'),
        ),
    ]
